package me.mmigas.gui;

public enum PageId {
    MAIN,
    COMPOSITIONMANAGER,
    UPDATE_COMPOSITION,
    CHOOSE_BLOCK_PAGE,
    PERCENTAGE_PAGE,
    RESET_PAGE,
    MINED_PERCENTAGE_PAGE,
    RESET_TIMER_SETTINGS,
    RESET_PERCENTAGE_SETTINGS;
}
