main: me.mmigas.AutoMines
name: MinesPlugin
description: A simple mine plugin
api-version: 1.14
version: 0.1 - Alpha
commands:
  AutoMines:
    description: AutoMines Base plugin
    usage: /AutoMines



